channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.6.0
  - cudatoolkit=10.1
  - rdkit
  - pip
  - pip:
      - -r requirements.txt
      - -f https://pytorch-geometric.com/whl/torch-1.6.0.html